/**
 * Embedded catalog of globally iconic songs for zero-latency ghost-text
 * suggestions. These are real, verifiable songs — the catalog only seeds the
 * local autocomplete; the authoritative verification still goes to iTunes.
 *
 * Kept intentionally compact (~150 entries) so it is fast to scan and cheap
 * to ship. Add entries as { artist, title } objects.
 */
export const POPULAR_CATALOG: ReadonlyArray<{ artist: string; title: string }> = [
  // Sting / The Police
  { artist: "Sting", title: "Fragile" },
  { artist: "Sting", title: "Desert Rose" },
  { artist: "Sting", title: "Russians" },
  { artist: "Sting", title: "Englishman in New York" },
  { artist: "Sting", title: "Fields of Gold" },
  { artist: "Sting", title: "Shape of My Heart" },
  { artist: "Sting", title: "All This Time" },
  { artist: "Sting", title: "If I Ever Lose My Faith in You" },
  { artist: "The Police", title: "Roxanne" },
  { artist: "The Police", title: "Every Breath You Take" },
  { artist: "The Police", title: "Message in a Bottle" },
  { artist: "The Police", title: "Don't Stand So Close to Me" },
  { artist: "The Police", title: "Walking on the Moon" },
  { artist: "The Police", title: "King of Pain" },
  // Michael Jackson
  { artist: "Michael Jackson", title: "Bad" },
  { artist: "Michael Jackson", title: "Billie Jean" },
  { artist: "Michael Jackson", title: "Thriller" },
  { artist: "Michael Jackson", title: "Beat It" },
  { artist: "Michael Jackson", title: "Smooth Criminal" },
  { artist: "Michael Jackson", title: "Man in the Mirror" },
  { artist: "Michael Jackson", title: "Black or White" },
  { artist: "Michael Jackson", title: "The Way You Make Me Feel" },
  { artist: "Michael Jackson", title: "Don't Stop 'Til You Get Enough" },
  { artist: "Michael Jackson", title: "Heal the World" },
  { artist: "Michael Jackson", title: "Rock with You" },
  // Queen
  { artist: "Queen", title: "Bohemian Rhapsody" },
  { artist: "Queen", title: "Love of My Life" },
  { artist: "Queen", title: "We Will Rock You" },
  { artist: "Queen", title: "We Are the Champions" },
  { artist: "Queen", title: "Don't Stop Me Now" },
  { artist: "Queen", title: "Somebody to Love" },
  { artist: "Queen", title: "Another One Bites the Dust" },
  { artist: "Queen", title: "Under Pressure" },
  { artist: "Queen", title: "Radio Ga Ga" },
  { artist: "Queen", title: "I Want to Break Free" },
  // The Beatles
  { artist: "The Beatles", title: "Yesterday" },
  { artist: "The Beatles", title: "Hey Jude" },
  { artist: "The Beatles", title: "Let It Be" },
  { artist: "The Beatles", title: "Come Together" },
  { artist: "The Beatles", title: "Something" },
  { artist: "The Beatles", title: "Here Comes the Sun" },
  { artist: "The Beatles", title: "Eleanor Rigby" },
  { artist: "The Beatles", title: "A Hard Day's Night" },
  { artist: "The Beatles", title: "All You Need Is Love" },
  { artist: "The Beatles", title: "Blackbird" },
  // Johnny Cash
  { artist: "Johnny Cash", title: "Hurt" },
  { artist: "Johnny Cash", title: "Ring of Fire" },
  { artist: "Johnny Cash", title: "I Walk the Line" },
  { artist: "Johnny Cash", title: "Folsom Prison Blues" },
  // Leonard Cohen
  { artist: "Leonard Cohen", title: "Hallelujah" },
  { artist: "Leonard Cohen", title: "Suzanne" },
  { artist: "Leonard Cohen", title: "Dance Me to the End of Love" },
  // Judas Priest / rock
  { artist: "Judas Priest", title: "Painkiller" },
  { artist: "Judas Priest", title: "Breaking the Law" },
  { artist: "AC/DC", title: "Back in Black" },
  { artist: "AC/DC", title: "Highway to Hell" },
  { artist: "AC/DC", title: "Thunderstruck" },
  { artist: "Guns N' Roses", title: "Sweet Child O' Mine" },
  { artist: "Guns N' Roses", title: "November Rain" },
  { artist: "Guns N' Roses", title: "Welcome to the Jungle" },
  { artist: "Led Zeppelin", title: "Stairway to Heaven" },
  { artist: "Led Zeppelin", title: "Whole Lotta Love" },
  { artist: "Led Zeppelin", title: "Kashmir" },
  { artist: "Pink Floyd", title: "Another Brick in the Wall" },
  { artist: "Pink Floyd", title: "Comfortably Numb" },
  { artist: "Pink Floyd", title: "Wish You Were Here" },
  { artist: "Metallica", title: "Enter Sandman" },
  { artist: "Metallica", title: "Nothing Else Matters" },
  { artist: "Metallica", title: "Master of Puppets" },
  { artist: "Nirvana", title: "Smells Like Teen Spirit" },
  { artist: "Nirvana", title: "Come as You Are" },
  { artist: "Nirvana", title: "Heart-Shaped Box" },
  // Pop / soul classics
  { artist: "Adele", title: "Someone Like You" },
  { artist: "Adele", title: "Rolling in the Deep" },
  { artist: "Adele", title: "Hello" },
  { artist: "Adele", title: "Set Fire to the Rain" },
  { artist: "Whitney Houston", title: "I Will Always Love You" },
  { artist: "Whitney Houston", title: "I Wanna Dance with Somebody" },
  { artist: "Whitney Houston", title: "Greatest Love of All" },
  { artist: "Madonna", title: "Like a Prayer" },
  { artist: "Madonna", title: "Vogue" },
  { artist: "Madonna", title: "Material Girl" },
  { artist: "Madonna", title: "Frozen" },
  { artist: "Madonna", title: "Hung Up" },
  { artist: "Madonna", title: "Ray of Light" },
  { artist: "Madonna", title: "Like a Virgin" },
  { artist: "Madonna", title: "La Isla Bonita" },
  { artist: "Madonna", title: "Music" },
  { artist: "Prince", title: "Purple Rain" },
  { artist: "Prince", title: "Kiss" },
  { artist: "Prince", title: "When Doves Cry" },
  { artist: "David Bowie", title: "Heroes" },
  { artist: "David Bowie", title: "Space Oddity" },
  { artist: "David Bowie", title: "Life on Mars?" },
  { artist: "Elton John", title: "Your Song" },
  { artist: "Elton John", title: "Rocket Man" },
  { artist: "Elton John", title: "Tiny Dancer" },
  { artist: "Elvis Presley", title: "Can't Help Falling in Love" },
  { artist: "Elvis Presley", title: "Suspicious Minds" },
  { artist: "Elvis Presley", title: "Jailhouse Rock" },
  { artist: "Frank Sinatra", title: "My Way" },
  { artist: "Frank Sinatra", title: "Fly Me to the Moon" },
  { artist: "Frank Sinatra", title: "New York, New York" },
  { artist: "Bob Dylan", title: "Like a Rolling Stone" },
  { artist: "Bob Dylan", title: "Blowin' in the Wind" },
  { artist: "Bob Dylan", title: "Knockin' on Heaven's Door" },
  { artist: "Bob Marley", title: "No Woman, No Cry" },
  { artist: "Bob Marley", title: "Three Little Birds" },
  { artist: "Bob Marley", title: "Redemption Song" },
  { artist: "Aretha Franklin", title: "Respect" },
  { artist: "Aretha Franklin", title: "Think" },
  { artist: "Stevie Wonder", title: "Superstition" },
  { artist: "Stevie Wonder", title: "Isn't She Lovely" },
  { artist: "Stevie Wonder", title: "Sir Duke" },
  { artist: "Lionel Richie", title: "Hello" },
  { artist: "Lionel Richie", title: "All Night Long (All Night)" },
  { artist: "Lionel Richie", title: "Say You, Say Me" },
  // Modern pop
  { artist: "Beyoncé", title: "Halo" },
  { artist: "Beyoncé", title: "Single Ladies (Put a Ring on It)" },
  { artist: "Beyoncé", title: "Crazy in Love" },
  { artist: "Taylor Swift", title: "Shake It Off" },
  { artist: "Taylor Swift", title: "Blank Space" },
  { artist: "Taylor Swift", title: "Love Story" },
  { artist: "Ed Sheeran", title: "Shape of You" },
  { artist: "Ed Sheeran", title: "Perfect" },
  { artist: "Ed Sheeran", title: "Thinking Out Loud" },
  { artist: "Billie Eilish", title: "Bad Guy" },
  { artist: "Billie Eilish", title: "Ocean Eyes" },
  { artist: "Billie Eilish", title: "Happier Than Ever" },
  { artist: "The Weeknd", title: "Blinding Lights" },
  { artist: "The Weeknd", title: "Starboy" },
  { artist: "The Weeknd", title: "Can't Feel My Face" },
  { artist: "Dua Lipa", title: "Levitating" },
  { artist: "Dua Lipa", title: "Don't Start Now" },
  { artist: "Dua Lipa", title: "New Rules" },
  { artist: "Coldplay", title: "Yellow" },
  { artist: "Coldplay", title: "Fix You" },
  { artist: "Coldplay", title: "Viva la Vida" },
  { artist: "Coldplay", title: "The Scientist" },
  { artist: "U2", title: "With or Without You" },
  { artist: "U2", title: "One" },
  { artist: "U2", title: "Beautiful Day" },
  { artist: "Radiohead", title: "Creep" },
  { artist: "Radiohead", title: "Karma Police" },
  { artist: "Radiohead", title: "No Surprises" },
  { artist: "Oasis", title: "Wonderwall" },
  { artist: "Oasis", title: "Don't Look Back in Anger" },
  { artist: "Oasis", title: "Champagne Supernova" },
  { artist: "Arctic Monkeys", title: "Do I Wanna Know?" },
  { artist: "Arctic Monkeys", title: "R U Mine?" },
  { artist: "Arctic Monkeys", title: "505" },
  // 90s / 2000s pop & rock hits
  { artist: "Britney Spears", title: "...Baby One More Time" },
  { artist: "Britney Spears", title: "Toxic" },
  { artist: "Britney Spears", title: "Oops!... I Did It Again" },
  { artist: "Backstreet Boys", title: "I Want It That Way" },
  { artist: "Backstreet Boys", title: "Everybody (Backstreet's Back)" },
  { artist: "Spice Girls", title: "Wannabe" },
  { artist: "Spice Girls", title: "Spice Up Your Life" },
  { artist: "Christina Aguilera", title: "Genie in a Bottle" },
  { artist: "Christina Aguilera", title: "Beautiful" },
  { artist: "Shakira", title: "Whenever, Wherever" },
  { artist: "Shakira", title: "Hips Don't Lie" },
  { artist: "Shakira", title: "Underneath Your Clothes" },
  { artist: "Robbie Williams", title: "Angels" },
  { artist: "Robbie Williams", title: "Feel" },
  { artist: "Robbie Williams", title: "Rock DJ" },
  { artist: "Ricky Martin", title: "Livin' la Vida Loca" },
  { artist: "Destiny's Child", title: "Say My Name" },
  { artist: "Destiny's Child", title: "Survivor" },
  { artist: "TLC", title: "No Scrubs" },
  { artist: "TLC", title: "Waterfalls" },
  { artist: "Linkin Park", title: "In the End" },
  { artist: "Linkin Park", title: "Numb" },
  { artist: "Linkin Park", title: "Crawling" },
  { artist: "Green Day", title: "Boulevard of Broken Dreams" },
  { artist: "Green Day", title: "American Idiot" },
  { artist: "Green Day", title: "Basket Case" },
  { artist: "Red Hot Chili Peppers", title: "Californication" },
  { artist: "Red Hot Chili Peppers", title: "Under the Bridge" },
  { artist: "Red Hot Chili Peppers", title: "Scar Tissue" },
  { artist: "R.E.M.", title: "Losing My Religion" },
  { artist: "R.E.M.", title: "Everybody Hurts" },
  { artist: "Bon Jovi", title: "Livin' on a Prayer" },
  { artist: "Bon Jovi", title: "It's My Life" },
  { artist: "Bon Jovi", title: "Always" },
  { artist: "Aerosmith", title: "I Don't Want to Miss a Thing" },
  { artist: "Aerosmith", title: "Crazy" },
  { artist: "Celine Dion", title: "My Heart Will Go On" },
  { artist: "Celine Dion", title: "Because You Loved Me" },
  { artist: "Mariah Carey", title: "Hero" },
  { artist: "Mariah Carey", title: "We Belong Together" },
  { artist: "Mariah Carey", title: "Always Be My Baby" },
  { artist: "Alanis Morissette", title: "Ironic" },
  { artist: "Alanis Morissette", title: "You Oughta Know" },
  { artist: "No Doubt", title: "Don't Speak" },
  { artist: "The Cranberries", title: "Zombie" },
  { artist: "The Cranberries", title: "Linger" },
  { artist: "Eurythmics", title: "Sweet Dreams (Are Made of This)" },
  { artist: "George Michael", title: "Careless Whisper" },
  { artist: "George Michael", title: "Faith" },
  { artist: "Eric Clapton", title: "Tears in Heaven" },
  { artist: "Eric Clapton", title: "Wonderful Tonight" },
  { artist: "Bryan Adams", title: "(Everything I Do) I Do It for You" },
  { artist: "Bryan Adams", title: "Summer of '69" },
  { artist: "Scorpions", title: "Wind of Change" },
  { artist: "Scorpions", title: "Still Loving You" },
  { artist: "Roxette", title: "It Must Have Been Love" },
  { artist: "Roxette", title: "Listen to Your Heart" },
  { artist: "a-ha", title: "Take On Me" },
  { artist: "ABBA", title: "Dancing Queen" },
  { artist: "ABBA", title: "Mamma Mia" },
  { artist: "ABBA", title: "The Winner Takes It All" },
  // R&B / hip-hop touchstones
  { artist: "Lauryn Hill", title: "Doo Wop (That Thing)" },
  { artist: "Lauryn Hill", title: "Ex-Factor" },
  { artist: "OutKast", title: "Hey Ya!" },
  { artist: "OutKast", title: "Ms. Jackson" },
  { artist: "Eminem", title: "Lose Yourself" },
  { artist: "Eminem", title: "Stan" },
  { artist: "Eminem", title: "The Real Slim Shady" },
  { artist: "Tupac Shakur", title: "Changes" },
  { artist: "Tupac Shakur", title: "California Love" },
  { artist: "The Notorious B.I.G.", title: "Juicy" },
  { artist: "The Notorious B.I.G.", title: "Big Poppa" },
  { artist: "Kanye West", title: "Stronger" },
  { artist: "Kanye West", title: "Gold Digger" },
  { artist: "Kanye West", title: "Heartless" },
  // Turkish classics (app language is Turkish)
  { artist: "Tarkan", title: "Dudu" },
  { artist: "Tarkan", title: "Şımarık" },
  { artist: "Tarkan", title: "Kuzu Kuzu" },
  { artist: "Sezen Aksu", title: "Geri Dön" },
  { artist: "Sezen Aksu", title: "Tükeneceğiz" },
  { artist: "Barış Manço", title: "Dönence" },
  { artist: "Barış Manço", title: "Gülpembe" },
  { artist: "Cem Karaca", title: "Resimdeki Gözyaşları" },
  { artist: "Cem Karaca", title: "Tamirci Çırağı" },
  { artist: "Müslüm Gürses", title: "Hangimiz Sevmedik" },
  { artist: "Ajda Pekkan", title: "Hoşgör Sen" },
  { artist: "Ajda Pekkan", title: "Sana Ne Kime Ne" },
  { artist: "MFÖ", title: "Ele Güne Karşı" },
  { artist: "MFÖ", title: "Sakın Gelme" },
  { artist: "Sertab Erener", title: "Everyway That I Can" },
];
