/**
 * SceneRoom — the application's fixed global environment: a carved-wood
 * library interior whose lighting and palette adapt to the music while the
 * furniture itself never moves (Sting Rule II).
 *
 * The room is a build-time rendered imagery layer (`room-backdrop-<theme>.png`,
 * procedurally generated by `scripts/generate-room-backdrop.mjs` — real
 * raster texture with wood grain, lamp spill and vignette) over the theme's
 * wall gradient as fallback color. No flat CSS/DOM vector furniture is drawn
 * at runtime. The cards stand ON the desk; this module only renders the
 * environment behind them.
 */
import type { ReactNode } from "react";

import backdropGothic from "@/assets/room-backdrop-gothic.png";
import backdropGrunge from "@/assets/room-backdrop-grunge.png";
import backdropHiphop from "@/assets/room-backdrop-hiphop.png";
import backdropJazz from "@/assets/room-backdrop-jazz.png";
import backdropReggae from "@/assets/room-backdrop-reggae.png";
import backdropSoul from "@/assets/room-backdrop-soul.png";
import backdropSynth from "@/assets/room-backdrop-synth.png";

import { SCENE_PALETTES, type ScenePalette, type SceneThemeId } from "./scenePalettes";

export type { SceneThemeId } from "./scenePalettes";
export type { ScenePalette as SceneTheme } from "./scenePalettes";

/** Theme palette lookup kept for callers that still resolve colors. */
export const SCENE_THEMES = SCENE_PALETTES;

const BACKDROPS: Record<SceneThemeId, string> = {
  gothic: backdropGothic,
  reggae: backdropReggae,
  synth: backdropSynth,
  jazz: backdropJazz,
  soul: backdropSoul,
  grunge: backdropGrunge,
  hiphop: backdropHiphop,
};

/**
 * The fixed library room. Children render over the desk zone — the backdrop
 * image supplies shelves, desk, lamp and boxes as real texture.
 */
export function SceneRoom({ themeId, children }: { themeId: SceneThemeId; children?: ReactNode }) {
  const theme = SCENE_PALETTES[themeId];
  return (
    <div
      data-testid={`scene-room-${themeId}`}
      className="pointer-events-none absolute inset-0 overflow-hidden"
      style={{ background: `linear-gradient(to bottom, ${theme.wall[0]}, ${theme.wall[1]})` }}
    >
      {/* Rendered room backdrop — carved wood shelves, desk, lamp, boxes. */}
      <span
        aria-hidden
        data-testid={`scene-backdrop-${themeId}`}
        className="absolute inset-0"
        style={{
          backgroundImage: `url(${BACKDROPS[themeId]})`,
          backgroundSize: "cover",
          backgroundPosition: "center",
        }}
      />
      {/* Ambient room light — the theme's personality over the texture. */}
      <span
        aria-hidden
        className="absolute inset-0"
        style={{
          background: `radial-gradient(ellipse at 14% 46%, ${theme.glow}2e 0%, transparent 52%)`,
          mixBlendMode: "screen",
        }}
      />
      {/* The card zone — children stand on the desk. */}
      <div className="pointer-events-auto absolute inset-0">{children}</div>
    </div>
  );
}
